default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_520_ci
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: valetbike_development
<<<<<<< HEAD
  username: root
  password: Tevy194194
=======
  username: root <%= ENV['MYSQL_USERNAME'] || '' %>
  password: Grace425 <%= ENV['PASSWORD'] || '' %>
>>>>>>> cdfa083dd0f91baf210e7cc9f8c92486b5915087

test:
  <<: *default
  database: valetbike_test
  username: root
<<<<<<< HEAD
  password: Tevy194194
=======
  password: Grace425
>>>>>>> cdfa083dd0f91baf210e7cc9f8c92486b5915087

production:
  <<: *default
  database: valetbike_production
  username: root
<<<<<<< HEAD
  password: Tevy194194
=======
  password: Grace425
>>>>>>> cdfa083dd0f91baf210e7cc9f8c92486b5915087
